#
# Glean Client API
# # Introduction These are the public APIs to enable implementing a custom client interface to the Glean system.  # Usage guidelines This API is evolving fast. Glean will provide advance notice of any planned backwards incompatible changes along with a 6-month sunset period for anything that requires developers to adopt the new versions.  # SDK Client bindings for the API can be generated for most popular languages (Python, Java, NodeJS, etc). To do so:  Download the OpenAPI specification for the API, by clicking on one of the following options: 1. [Download JSON specification](https://api.redocly.com/registry/bundle/glean/Glean%20Client%20API%20SDK%20source/v1/openapi.json?branch=main&download=true) 2. [Download YAML specification](https://api.redocly.com/registry/bundle/glean/Glean%20Client%20API%20SDK%20source/v1/openapi.yaml?branch=main&download=true)  Use [openapi-generator-cli](https://github.com/OpenAPITools/openapi-generator-cli) to generate bindings for your language of choice, for example: ```bash shell $ npx @openapitools/openapi-generator-cli@latest generate -i client_api.yaml -g go ```  To see available languages: ```bash shell $ npx @openapitools/openapi-generator-cli@latest list ```  Determine the host you need to connect to. This will be the URL of the backend for your Glean deployment, for example, customer-be.glean.com 
# Version: 0.9.0
# Contact: support@glean.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

version: 1.0.{build}
image:
  - Visual Studio 2019 # PWSH 7.x
  #- Visual Studio 2017 # PS 5.x, PWSH 6.x
  #- Ubuntu # PWSH 6.x
  # ref: https://www.appveyor.com/docs/windows-images-software/
install:
  - pwsh: $PSVersionTable.PSVersion
  - pwsh: Install-Module Pester -Force -Scope CurrentUser
build: off
test_script:
  - pwsh: |
      .\Build.ps1
      Import-Module -Name '.\src\PSOpenAPITools'
      $Result = Invoke-Pester -PassThru
      if ($Result.FailedCount -gt 0) {
          $host.SetShouldExit($Result.FailedCount)
          exit $Result.FailedCount
      }
deploy_script:
  - pwsh: |
      if ($env:APPVEYOR_REPO_TAG -eq $true -and $null -ne $env:NuGetApiKey) {
          .\Build.ps1
          try {
              Publish-Module -NuGetApiKey $env:NuGetApiKey -Path .\src\PSOpenAPITools\ -Confirm:$False -Verbose
              Write-Host "Successfully published the PowerShell module."
          } catch {
              $host.SetShouldExit($LastExitCode)
              Write-Host "Error when running Publish-Module:"
              Write-Host $_
              exit
          }
      }
